# Generated by Django 4.2.7 on 2023-12-07 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='chats',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='rasa_chat_app.tickets'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ext_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('In-Progress', 'In-Progress'), ('Resolved', 'Resolved'), ('Disposed', 'Disposed')], default='Initiated', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 13, 24, 19, 700690)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 13, 24, 19, 701572)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='document_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chats',
            name='response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 13, 24, 19, 701076)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='document_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
