# Generated by Django 4.2.7 on 2023-12-08 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0002_remove_tickets_ticket_id_chats_ticket_tickets_ext_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 4, 46, 16, 937649)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 4, 46, 16, 938839)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 4, 46, 16, 938171)),
        ),
    ]
