# Generated by Django 4.2.7 on 2023-12-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0003_alter_chatroom_created_at_alter_chats_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 32, 37, 878584)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 32, 37, 879465)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 12, 32, 37, 879062)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ext_id',
            field=models.CharField(max_length=255),
        ),
    ]
