# Generated by Django 4.2.7 on 2023-12-11 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0005_alter_chatroom_created_at_alter_chats_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 6, 43, 42, 44658)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 6, 43, 42, 45569)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 6, 43, 42, 45148)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='document_url',
            field=models.FileField(blank=True, null=True, upload_to='static/documents'),
        ),
    ]
