# Generated by Django 4.2.7 on 2023-12-11 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0006_alter_chatroom_created_at_alter_chats_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='document_url',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='document_url',
            new_name='document',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 0, 12, 220779)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 0, 12, 221588)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 0, 12, 221173)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ext_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
