# Generated by Django 4.2.7 on 2023-12-11 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0007_rename_document_url_chats_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='chatroom',
        ),
        migrations.AddField(
            model_name='tickets',
            name='chat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='rasa_chat_app.chats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='text',
            field=models.CharField(default='sd', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 28, 49, 647366)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 28, 49, 647832)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 28, 49, 648247)),
        ),
    ]
