# Generated by Django 4.2.7 on 2023-12-11 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0008_remove_chats_ticket_remove_tickets_chatroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 10, 1, 19, 35602)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 10, 1, 19, 36073)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 10, 1, 19, 36488)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
