# Generated by Django 4.2.7 on 2023-12-12 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chat_app', '0009_alter_chatroom_created_at_alter_chats_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file')], default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 9, 54, 5, 845472)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 9, 54, 5, 845959)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 9, 54, 5, 846382)),
        ),
    ]
